# Generated by Django 4.2.7 on 2023-11-14 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("failure_counter", models.IntegerField()),
                ("last_update", models.DateTimeField(null=True)),
                ("next_update", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name": "RSS Feed",
                "verbose_name_plural": "RSS Feeds",
            },
        ),
        migrations.CreateModel(
            name="RSSPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(db_index=True, max_length=255)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssfeed"
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS Post",
                "verbose_name_plural": "RSS Posts",
            },
        ),
        migrations.CreateModel(
            name="RSSPostRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rsspost"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS Post Read",
                "verbose_name_plural": "RSS Post Reads",
            },
        ),
        migrations.CreateModel(
            name="RSSFeedFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rss.rssfeed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RSS Feed Follow",
                "verbose_name_plural": "RSS Feed Follows",
            },
        ),
    ]
