# Generated by Django 4.2.7 on 2023-11-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rssfeed",
            old_name="last_update",
            new_name="last_fetch",
        ),
        migrations.RenameField(
            model_name="rssfeed",
            old_name="next_update",
            new_name="next_fetch",
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="rssfeed",
            name="updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="rsspost",
            name="updated",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
