# Generated by Django 4.2.7 on 2023-11-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0003_alter_rssfeed_failure_counter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rsspost",
            old_name="updated",
            new_name="published",
        ),
    ]
