# Generated by Django 4.2.7 on 2023-11-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rss", "0004_rename_updated_rsspost_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rssfeedfollow",
            old_name="post",
            new_name="feed",
        ),
        migrations.AddConstraint(
            model_name="rssfeedfollow",
            constraint=models.UniqueConstraint(
                fields=("feed", "user"), name="feed_user_unique"
            ),
        ),
    ]
